version: '3'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./your-php-scripts-directory:/usr/src/myapp
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: music
      MYSQL_USER: user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
